version: '2'

services:
  mpi_head:
    build: .
    ports: 
      - "1337:8000"
    links:
      - mpi_node_first
    networks:
      - net
    expose: 
      - "22"
    environment:
      - PYTHONUNBUFFERED=0
    command: bash -c "/usr/sbin/sshd && sudo -u mpirun python3 /home/mpirun/parvaProject/manage.py runserver 0.0.0.0:8000"

  mpi_node_first:
    build: .
    ports:
      - "1338:8000"
    networks:
      - net
    expose: 
      - "22"

networks:
  net:
    driver: bridge

# docker-compose up --scale mpi_head=1 --scale mpi_node=3
# docker-compose exec --user mpirun --privileged mpi_head mpirun -n 1 python /home/mpirun/mpi4py_benchmarks/all_tests.py
# docker-compose down && docker-compose build && docker-compose up